CPRG102.FinalProject.AssetTracking/Controllers/AssignmentController.cs
using CPRG102.FinalProject.AssetTracking.Models;
using CPRG102.FinalProject.AssetTracking.ViewModels;
using CPRG102.FinalProject.BLL;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CPRG102.FinalProject.AssetTracking.Controllers
{
    public class AssignmentController : Controller
    {
        HttpClient ClientEmployee;
        string URLemployees = "http://localhost:63353/api/Employee";

        public AssignmentController()
        {
            ClientEmployee = new HttpClient();
            ClientEmployee.BaseAddress = new Uri(URLemployees);
            ClientEmployee.DefaultRequestHeaders.Accept.Clear();
            ClientEmployee.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        // GET: Assignment
        public async Task<ActionResult> Index()
        {
            HttpResponseMessage msg = await ClientEmployee.GetAsync(URLemployees);

            var employees = new List<Employee>();

            if (msg.IsSuccessStatusCode)
            {
                var data = msg.Content.ReadAsStringAsync().Result;
                employees = JsonConvert.DeserializeObject<List<Employee>>(data); //employee data
            }

            AssetTypeManager TypeMng = new AssetTypeManager();
            var Types = TypeMng.GetAssetTypes(); //get asset types

            AssetManager AssetMng = new AssetManager();
            var Assets = AssetMng.GetAssets();//get all assets            

            var UnassignedEmployee = employees //Collection of employee who haven't been assigned any asset
                .Where(o => Assets.All(a => o.EmployeeNumber != a.AssignedTo))
                .Select(o => new Employee
                {
                    Id = o.Id,
                    EmployeeNumber = o.EmployeeNumber,
                    FirstName = o.FirstName,
                    LastName = o.LastName,
                    Position = o.Position,
                    Phone = o.Phone,
                    DepartmentId = o.DepartmentId
                }).ToList();

            var assetTypeList = new List<SelectListItem>();

            foreach (var type in Types)
            {
                assetTypeList.Add(new SelectListItem { Value = type.Id.ToString(), Text = type.Name });
            }

            var employeesList = UnassignedEmployee.Select(o => new SelectListItem { Value = o.EmployeeNumber, Text = $"{o.FirstName} {o.LastName} (Phone: {o.Phone})" });

            AssignmentViewModel ViewModel = new AssignmentViewModel();

            ViewModel.AssetType = assetTypeList;
            ViewModel.UnassignedEmployees = employeesList;

            return View(ViewModel);
        }

        public JsonResult GetAssetByType(int id)
        {
            AssetManager manager = new AssetManager();

            var assets = manager.AssetsByType(id).Where(o => o.AssignedTo == null).Select(o => new SelectListItem { Value = o.Id.ToString(), Text = $"{o.Model.Name} ({o.Manufacturer.Name})" });

            return Json(assets, "text/json", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ProcessData(FormCollection formData)
        {
            AssetManager manager = new AssetManager();
            var asset = manager.Find(int.Parse(formData["Assets"])); //get asset by selected drop down list
            asset.AssignedTo = formData["Employees"];

            manager.UpdateAsset(asset); //update asset information (method from AssetManager)

            return RedirectToAction("Index");
        }
    }
}

CPRG102.FinalProject.AssetTracking/Controllers/NewAssetController.cs
using CPRG102.FinalProject.AssetTracking.Models;
using CPRG102.FinalProject.AssetTracking.ViewModels;
using CPRG102.FinalProject.BLL;
using CPRG102.FinalProject.Domain;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CPRG102.FinalProject.AssetTracking.Controllers
{
    public class NewAssetController : Controller
    {
        HttpClient ClientEmployee;
        string URLemployees = "http://localhost:63353/api/Employee";

        public NewAssetController()
        {
            ClientEmployee = new HttpClient();
            ClientEmployee.BaseAddress = new Uri(URLemployees);
            ClientEmployee.DefaultRequestHeaders.Accept.Clear();
            ClientEmployee.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }
        
        // GET: NewAsset
        public async Task<ActionResult> Index()
        {
            HttpResponseMessage msg = await ClientEmployee.GetAsync(URLemployees);

            var employees = new List<Employee>();

            if (msg.IsSuccessStatusCode)
            {
                var data = msg.Content.ReadAsStringAsync().Result;
                employees = JsonConvert.DeserializeObject<List<Employee>>(data);
            }

            AssetTypeManager TypeMng = new AssetTypeManager();
            ManufacturerManager ManufacturerMng = new ManufacturerManager();
            ModelManager ModelMng = new ModelManager();
            var Types = TypeMng.GetAssetTypes();
            var Manufaturers = ManufacturerMng.GetManufacturers();
            var Models = ModelMng.GetModels();

            var TypesList = new List<SelectListItem>();
            var ManufacturersList = new List<SelectListItem>();
            var ModelsList = new List<SelectListItem>();
            var EmployeesList = new List<SelectListItem>();

            foreach(var type in Types)
            {
                TypesList.Add(new SelectListItem { Value = type.Id.ToString(), Text = type.Name });
            }

            foreach(var manufacturer in Manufaturers)
            {
                ManufacturersList.Add(new SelectListItem { Value = manufacturer.Id.ToString(), Text = manufacturer.Name });
            }

            foreach(var model in Models)
            {
                ModelsList.Add(new SelectListItem { Value = model.Id.ToString(), Text = model.Name });
            }

            foreach(var employee in employees)
            {
                //EmployeeNumber is used instead of ID
                EmployeesList.Add(new SelectListItem { Value = employee.EmployeeNumber, Text = $"{employee.FirstName} {employee.LastName}" });
            }

            NewAssetViewModel ViewModel = new NewAssetViewModel();
            ViewModel.AssetType = TypesList;
            ViewModel.Manufacturer = ManufacturersList;
            ViewModel.Model = ModelsList;
            ViewModel.Employees = EmployeesList;

            return View(ViewModel);
        }

        [HttpPost]
        public ActionResult ProcessData(FormCollection formData)
        {
            try
            {
                AssetManager manager = new AssetManager();
                Asset _asset = new Asset();

                _asset.AssetTypeId = int.Parse(formData["AssetTypes"]);
                _asset.ManufacturerId = int.Parse(formData["Manufacturer"]);
                _asset.ModelId = int.Parse(formData["Model"]);
                _asset.AssignedTo = formData["Employee"];

                manager.AddAsset(_asset);

                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }         
        }
    }
}

CPRG102.FinalProject.AssetTracking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/knockout-3.4.2.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <style>
        hr.style-eight {
            padding: 0;
            border: none;
            border-top: medium double #333;
            color: #333;
            text-align: center;
        }
       hr.style-eight:after {
                content: "§";
                display: inline-block;
                position: relative;
                top: -0.7em;
                font-size: 1.5em;
                padding: 0 0.25em;
                background: white;
            }
        .rowNewAssetDropDown {
            width: 300px;
            height: 50px;
            vertical-align: middle;
            text-align: center
        }
        .rowNewAssetDropType {
            width: 200px;
            height: 50px;
            vertical-align: middle
        }
    </style>
</head>
<body> 
    <div id="image" style="width:100%;">
        <div>
            <img src="~/Images/tech2.png" width="110" height="110" style=" float:right;margin: 15px 80px 15px 15px"/>
        </div>
    </div>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Asset Tracking Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li> @Html.ActionLink("Home", "Index", "Home") </li>
                    <li> @Html.ActionLink("New Asset", "Index", "NewAsset") </li>
                    <li> @Html.ActionLink("Assignments", "Index", "Assignment") </li>
                </ul>
            </div>
        </div>
    </div>
    <br /><br /> <br /> 
    <div class="container body-content">
        @RenderBody()
        <hr />      
    </div>

 
    <div id="footer">      
        <div class="wrap">
            <p>&copy; @DateTime.Now.Year - CPRG-102 Asset Tracking Application Final Project </p>   
        </div>
    </div>

    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>